# Uncomment the next line to define a global platform for your project
#platform :ios, '9.0'

target 'TWTW' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

 # Networking
  pod 'Alamofire'

  # UI Layout
  pod 'SnapKit', '~> 5.6.0'

  # Reactive Programming
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'
  pod 'RxKakaoSDK'
  pod 'RxAlamofire'

  # Utility
  pod 'KeychainSwift', '~> 20.0'
  
  # Maps
  pod 'NMapsMap'
 
  # Pods for TWTW

 post_install do |installer|
   installer.pods_project.targets.each do |target|
     target.build_configurations.each do |config|
       config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
     end
   end
 end
end
